#include "Audio/__internalConfig/LoggerConfig.h"
#include "SDLMixerLibrary.h"

#define SKA_MIXER_LIB_NAME_DEFINE(ENUM, NAME) \
	SKA_LIB_NAME_DEFINE(ska::MixerIdNamedFunction, static_cast<int>(ska::MixerCalls::ENUM), NAME)

SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_INIT, "Mix_Init");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_OPEN_AUDIO, "Mix_OpenAudio");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_CLOSE_AUDIO, "Mix_CloseAudio");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_QUIT, "Mix_Quit");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_ALLOCATE_CHANNELS, "Mix_AllocateChannels");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_LOAD_MUSIC, "Mix_LoadMUS");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_PLAY_MUSIC, "Mix_PlayMusic");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_PAUSE_MUSIC, "Mix_PauseMusic");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_VOLUME_MUSIC, "Mix_VolumeMusic");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_FREE_MUSIC, "Mix_FreeMusic");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_FREE_CHUNK, "Mix_FreeChunk");
SKA_MIXER_LIB_NAME_DEFINE(SDL_MIXER_WAV_RW, "Mix_LoadWAV_RW");

const ska::SDLMixerLibrary& ska::SDLMixerLibrary::get() {
	static const SDLMixerLibrary instance;
	return instance;	
}